DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS tasks;

CREATE TABLE cards(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL, 
  num_tasks INTEGER NOT NULL
);

CREATE TABLE tasks(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pcard INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  torder INTEGER NOT NULL,
  FOREIGN KEY (pcard) REFERENCES cards (id)
);